#!/usr/bin/env bash

INPUT=$1
CODE=$(echo $INPUT| cut -f 1 -d '.')

./english.native < $CODE.ell > $CODE.ll
/usr/local/opt/llvm/bin/llc $CODE.ll > $CODE.s
cc -o $CODE.exe $CODE.s c-code.o
./$CODE.exe


